### ISSUE TITLE
When completing checkout with a virtual product Billing Address is not saved to SP

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-offline-payments#7]
PRs: subscribepro/subscribepro-magento2-ext#244, OP [#8 ](https://github.com/subscribepro/subscribepro-magento2-offline-payments/pull/8)  SPHP [#52](https://github.com/subscribepro/subscribepro-php/pull/52)

Complete checkout for a subscription using checkmo payment method for a virtual product.   The customer and subscription will be created in Magento, but there will be no associated billing address which is required.

https://www.loom.com/share/858c4c2782dc4635805ab8773712b620?sid=06add6b6-d618-4ce1-80d2-a729d4f59624

**Comment by eugene-shab** [comment]
@garthbrantley Fixes have been added to two repositories, please keep this in mind
